[package]
name = "vtf"
description = "Valve Texture format library for Rust"
version = "0.1.5"
license = "MIT"
authors = ["Roman Shishkin <spark@uwtech.org>", "Robin Appelman <robin@icewind.nl>"]
repository = "https://github.com/roman901/vtf-rs"
edition = "2018"

[dependencies]
image = "0.23.14"
texpresso = "2.0.1"
err-derive = "0.2.2"
parse-display = "0.1.1"
num_enum = "0.4"
byteorder = "1.3.2"
